// This file is generated by scripts/gen-assets.ts. Do not edit.
// It contains static imports so Bun can inline all assets.

import SP_update_claudemd from '../system-prompts/update-claudemd-prompt.md' with { type: 'text' }
import SP_refactor from '../system-prompts/refactor-prompt.md' with { type: 'text' }
import SP_orient from '../system-prompts/orient-prompt.md' with { type: 'text' }
import SP_designer from '../system-prompts/designer-prompt.md' with { type: 'text' }
import SP_brainstorm from '../system-prompts/brainstorm-prompt.md' with { type: 'text' }
import SP_builder from '../system-prompts/builder-prompt.md' with { type: 'text' }
import SP_prompt_improver from '../system-prompts/prompt-improver-prompt.md' with { type: 'text' }
import SP_fix from '../system-prompts/fix-prompt.md' with { type: 'text' }
import SP_feature from '../system-prompts/feature-prompt.md' with { type: 'text' }
import PR_refactor_prompt from '../prompts/refactor-prompt.md' with { type: 'text' }
import PR_claude_mix from '../prompts/claude-mix.md' with { type: 'text' }
import PR_cc from '../prompts/cc.md' with { type: 'text' }
import PR_github_examples from '../prompts/github-examples.md' with { type: 'text' }
import ST_contain from '../settings/contain.settings.json' with { type: 'json' }
import ST_refactor from '../settings/refactor.settings.json' with { type: 'json' }
import ST_orient from '../settings/orient.settings.json' with { type: 'json' }
import ST_update_claudemd from '../settings/update-claudemd.settings.json' with { type: 'json' }
import ST_builder from '../settings/builder.settings.json' with { type: 'json' }
import ST_brainstorm from '../settings/brainstorm.settings.json' with { type: 'json' }
import ST_planner from '../settings/planner.settings.json' with { type: 'json' }
import ST_designer from '../settings/designer.settings.json' with { type: 'json' }
import MCP_brainstorm from '../settings/brainstorm.mcp.json' with { type: 'json' }
import MCP_designer from '../settings/designer.mcp.json' with { type: 'json' }
import MCP_orient from '../settings/orient.mcp.json' with { type: 'json' }
import MCP_contain from '../settings/contain.mcp.json' with { type: 'json' }
import MCP_refactor from '../settings/refactor.mcp.json' with { type: 'json' }
import MCP_builder from '../settings/builder.mcp.json' with { type: 'json' }
import MCP_planner from '../settings/planner.mcp.json' with { type: 'json' }
import MCP_update_claudemd from '../settings/update-claudemd.mcp.json' with { type: 'json' }

export const SYSTEM_PROMPTS = {
  'brainstorm': SP_brainstorm,
  'builder': SP_builder,
  'designer': SP_designer,
  'feature': SP_feature,
  'fix': SP_fix,
  'orient': SP_orient,
  'prompt-improver': SP_prompt_improver,
  'refactor': SP_refactor,
  'update-claudemd': SP_update_claudemd
};
export const PROMPTS = {
  'cc': PR_cc,
  'claude-mix': PR_claude_mix,
  'github-examples': PR_github_examples,
  'refactor-prompt': PR_refactor_prompt
};
export const SETTINGS = {
  'brainstorm': ST_brainstorm,
  'builder': ST_builder,
  'contain': ST_contain,
  'designer': ST_designer,
  'orient': ST_orient,
  'planner': ST_planner,
  'refactor': ST_refactor,
  'update-claudemd': ST_update_claudemd
};
export const MCP = {
  'brainstorm': MCP_brainstorm,
  'builder': MCP_builder,
  'contain': MCP_contain,
  'designer': MCP_designer,
  'orient': MCP_orient,
  'planner': MCP_planner,
  'refactor': MCP_refactor,
  'update-claudemd': MCP_update_claudemd
};
